# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Anasayfa.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1093, 826)
        MainWindow.setStyleSheet("QMainWindow {\n"
"    background-color:#ececec;\n"
"}\n"
"QTextEdit {\n"
"    border-width: 1px;\n"
"    border-style: solid;\n"
"    border-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgba(0, 113, 255, 255), stop:1 rgba(91, 171, 252, 255));\n"
"}\n"
"QPlainTextEdit {\n"
"    border-width: 1px;\n"
"    border-style: solid;\n"
"    border-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgba(0, 113, 255, 255), stop:1 rgba(91, 171, 252, 255));\n"
"}\n"
"QToolButton {\n"
"    border-style: solid;\n"
"    border-top-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgb(215, 215, 215), stop:1 rgb(222, 222, 222));\n"
"    border-right-color: qlineargradient(spread:pad, x1:0, y1:0.5, x2:1, y2:0.5, stop:0 rgb(217, 217, 217), stop:1 rgb(227, 227, 227));\n"
"    border-left-color: qlineargradient(spread:pad, x1:0, y1:0.5, x2:1, y2:0.5, stop:0 rgb(227, 227, 227), stop:1 rgb(217, 217, 217));\n"
"    border-bottom-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgb(215, 215, 215), stop:1 rgb(222, 222, 222));\n"
"    border-width: 1px;\n"
"    border-radius: 5px;\n"
"    color: rgb(0,0,0);\n"
"    padding: 2px;\n"
"    background-color: rgb(255,255,255);\n"
"}\n"
"QToolButton:hover{\n"
"    border-style: solid;\n"
"    border-top-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgb(195, 195, 195), stop:1 rgb(222, 222, 222));\n"
"    border-right-color: qlineargradient(spread:pad, x1:0, y1:0.5, x2:1, y2:0.5, stop:0 rgb(197, 197, 197), stop:1 rgb(227, 227, 227));\n"
"    border-left-color: qlineargradient(spread:pad, x1:0, y1:0.5, x2:1, y2:0.5, stop:0 rgb(227, 227, 227), stop:1 rgb(197, 197, 197));\n"
"    border-bottom-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgb(195, 195, 195), stop:1 rgb(222, 222, 222));\n"
"    border-width: 1px;\n"
"    border-radius: 5px;\n"
"    color: rgb(0,0,0);\n"
"    padding: 2px;\n"
"    background-color: rgb(255,255,255);\n"
"}\n"
"QToolButton:pressed{\n"
"    border-style: solid;\n"
"    border-top-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgb(215, 215, 215), stop:1 rgb(222, 222, 222));\n"
"    border-right-color: qlineargradient(spread:pad, x1:0, y1:0.5, x2:1, y2:0.5, stop:0 rgb(217, 217, 217), stop:1 rgb(227, 227, 227));\n"
"    border-left-color: qlineargradient(spread:pad, x1:0, y1:0.5, x2:1, y2:0.5, stop:0 rgb(227, 227, 227), stop:1 rgb(217, 217, 217));\n"
"    border-bottom-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgb(215, 215, 215), stop:1 rgb(222, 222, 222));\n"
"    border-width: 1px;\n"
"    border-radius: 5px;\n"
"    color: rgb(0,0,0);\n"
"    padding: 2px;\n"
"    background-color: rgb(142,142,142);\n"
"}\n"
"QPushButton{\n"
"    border-style: solid;\n"
"    border-top-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgb(215, 215, 215), stop:1 rgb(222, 222, 222));\n"
"    border-right-color: qlineargradient(spread:pad, x1:0, y1:0.5, x2:1, y2:0.5, stop:0 rgb(217, 217, 217), stop:1 rgb(227, 227, 227));\n"
"    border-left-color: qlineargradient(spread:pad, x1:0, y1:0.5, x2:1, y2:0.5, stop:0 rgb(227, 227, 227), stop:1 rgb(217, 217, 217));\n"
"    border-bottom-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgb(215, 215, 215), stop:1 rgb(222, 222, 222));\n"
"    border-width: 1px;\n"
"    border-radius: 5px;\n"
"    color: rgb(0,0,0);\n"
"    padding: 2px;\n"
"    background-color: rgb(255,255,255);\n"
"}\n"
"QPushButton::default{\n"
"    border-style: solid;\n"
"    border-top-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgb(215, 215, 215), stop:1 rgb(222, 222, 222));\n"
"    border-right-color: qlineargradient(spread:pad, x1:0, y1:0.5, x2:1, y2:0.5, stop:0 rgb(217, 217, 217), stop:1 rgb(227, 227, 227));\n"
"    border-left-color: qlineargradient(spread:pad, x1:0, y1:0.5, x2:1, y2:0.5, stop:0 rgb(227, 227, 227), stop:1 rgb(217, 217, 217));\n"
"    border-bottom-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgb(215, 215, 215), stop:1 rgb(222, 222, 222));\n"
"    border-width: 1px;\n"
"    border-radius: 5px;\n"
"    color: rgb(0,0,0);\n"
"    padding: 2px;\n"
"    background-color: rgb(255,255,255);\n"
"}\n"
"QPushButton:hover{\n"
"    border-style: solid;\n"
"    border-top-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgb(195, 195, 195), stop:1 rgb(222, 222, 222));\n"
"    border-right-color: qlineargradient(spread:pad, x1:0, y1:0.5, x2:1, y2:0.5, stop:0 rgb(197, 197, 197), stop:1 rgb(227, 227, 227));\n"
"    border-left-color: qlineargradient(spread:pad, x1:0, y1:0.5, x2:1, y2:0.5, stop:0 rgb(227, 227, 227), stop:1 rgb(197, 197, 197));\n"
"    border-bottom-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgb(195, 195, 195), stop:1 rgb(222, 222, 222));\n"
"    border-width: 1px;\n"
"    border-radius: 5px;\n"
"    color: rgb(0,0,0);\n"
"    padding: 2px;\n"
"    background-color: rgb(255,255,255);\n"
"}\n"
"QPushButton:pressed{\n"
"    border-style: solid;\n"
"    border-top-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgb(215, 215, 215), stop:1 rgb(222, 222, 222));\n"
"    border-right-color: qlineargradient(spread:pad, x1:0, y1:0.5, x2:1, y2:0.5, stop:0 rgb(217, 217, 217), stop:1 rgb(227, 227, 227));\n"
"    border-left-color: qlineargradient(spread:pad, x1:0, y1:0.5, x2:1, y2:0.5, stop:0 rgb(227, 227, 227), stop:1 rgb(217, 217, 217));\n"
"    border-bottom-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgb(215, 215, 215), stop:1 rgb(222, 222, 222));\n"
"    border-width: 1px;\n"
"    border-radius: 5px;\n"
"    color: rgb(0,0,0);\n"
"    padding: 2px;\n"
"    background-color: rgb(142,142,142);\n"
"}\n"
"QPushButton:disabled{\n"
"    border-style: solid;\n"
"    border-top-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgb(215, 215, 215), stop:1 rgb(222, 222, 222));\n"
"    border-right-color: qlineargradient(spread:pad, x1:0, y1:0.5, x2:1, y2:0.5, stop:0 rgb(217, 217, 217), stop:1 rgb(227, 227, 227));\n"
"    border-left-color: qlineargradient(spread:pad, x1:0, y1:0.5, x2:1, y2:0.5, stop:0 rgb(227, 227, 227), stop:1 rgb(217, 217, 217));\n"
"    border-bottom-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgb(215, 215, 215), stop:1 rgb(222, 222, 222));\n"
"    border-width: 1px;\n"
"    border-radius: 5px;\n"
"    color: #808086;\n"
"    padding: 2px;\n"
"    background-color: rgb(142,142,142);\n"
"}\n"
"QLineEdit {\n"
"    border-width: 1px; border-radius: 4px;\n"
"    border-style: solid;\n"
"    border-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgba(0, 113, 255, 255), stop:1 rgba(91, 171, 252, 255));\n"
"}\n"
"QLabel {\n"
"    color: #000000;\n"
"}\n"
"QLCDNumber {\n"
"    color: rgb(0, 113, 255, 255);\n"
"}\n"
"QProgressBar {\n"
"    text-align: center;\n"
"    color: rgb(240, 240, 240);\n"
"    border-width: 1px; \n"
"    border-radius: 10px;\n"
"    border-color: rgb(230, 230, 230);\n"
"    border-style: solid;\n"
"    background-color:rgb(207,207,207);\n"
"}\n"
"QProgressBar::chunk {\n"
"    background-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgba(49, 147, 250, 255), stop:1 rgba(34, 142, 255, 255));\n"
"    border-radius: 10px;\n"
"}\n"
"QMenuBar {\n"
"    background-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgba(207, 209, 207, 255), stop:1 rgba(230, 229, 230, 255));\n"
"}\n"
"QMenuBar::item {\n"
"    color: #000000;\n"
"      spacing: 3px;\n"
"      padding: 1px 4px;\n"
"    background-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgba(207, 209, 207, 255), stop:1 rgba(230, 229, 230, 255));\n"
"}\n"
"\n"
"QMenuBar::item:selected {\n"
"      background-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgba(0, 113, 255, 255), stop:1 rgba(91, 171, 252, 255));\n"
"    color: #FFFFFF;\n"
"}\n"
"QMenu::item:selected {\n"
"    border-style: solid;\n"
"    border-top-color: transparent;\n"
"    border-right-color: transparent;\n"
"    border-left-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgba(0, 113, 255, 255), stop:1 rgba(91, 171, 252, 255));\n"
"    border-bottom-color: transparent;\n"
"    border-left-width: 2px;\n"
"    color: #000000;\n"
"    padding-left:15px;\n"
"    padding-top:4px;\n"
"    padding-bottom:4px;\n"
"    padding-right:7px;\n"
"}\n"
"QMenu::item {\n"
"    border-style: solid;\n"
"    border-top-color: transparent;\n"
"    border-right-color: transparent;\n"
"    border-left-color: transparent;\n"
"    border-bottom-color: transparent;\n"
"    border-bottom-width: 1px;\n"
"    color: #000000;\n"
"    padding-left:17px;\n"
"    padding-top:4px;\n"
"    padding-bottom:4px;\n"
"    padding-right:7px;\n"
"}\n"
"QTabWidget {\n"
"    color:rgb(0,0,0);\n"
"    background-color:#000000;\n"
"}\n"
"QTabWidget::pane {\n"
"        border-color: rgb(223,223,223);\n"
"        background-color:rgb(226,226,226);\n"
"        border-style: solid;\n"
"        border-width: 2px;\n"
"        border-radius: 6px;\n"
"}\n"
"QTabBar::tab:first {\n"
"    border-style: solid;\n"
"    border-left-width:1px;\n"
"    border-right-width:0px;\n"
"    border-top-width:1px;\n"
"    border-bottom-width:1px;\n"
"    border-top-color: rgb(209,209,209);\n"
"    border-left-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgba(209, 209, 209, 209), stop:1 rgba(229, 229, 229, 229));\n"
"    border-bottom-color: rgb(229,229,229);\n"
"    border-top-left-radius: 4px;\n"
"    border-bottom-left-radius: 4px;\n"
"    color: #000000;\n"
"    padding: 3px;\n"
"    margin-left:0px;\n"
"    background-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgba(247, 247, 247, 255), stop:1 rgba(255, 255, 255, 255));\n"
"}\n"
"QTabBar::tab:last {\n"
"    border-style: solid;\n"
"    border-width:1px;\n"
"    border-top-color: rgb(209,209,209);\n"
"    border-left-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgba(209, 209, 209, 209), stop:1 rgba(229, 229, 229, 229));\n"
"    border-right-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgba(209, 209, 209, 209), stop:1 rgba(229, 229, 229, 229));\n"
"    border-bottom-color: rgb(229,229,229);\n"
"    border-top-right-radius: 4px;\n"
"    border-bottom-right-radius: 4px;\n"
"    color: #000000;\n"
"    padding: 3px;\n"
"    margin-left:0px;\n"
"    background-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgba(247, 247, 247, 255), stop:1 rgba(255, 255, 255, 255));\n"
"}\n"
"QTabBar::tab {\n"
"    border-style: solid;\n"
"    border-top-width:1px;\n"
"    border-bottom-width:1px;\n"
"    border-left-width:1px;\n"
"    border-top-color: rgb(209,209,209);\n"
"    border-left-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgba(209, 209, 209, 209), stop:1 rgba(229, 229, 229, 229));\n"
"    border-bottom-color: rgb(229,229,229);\n"
"    color: #000000;\n"
"    padding: 3px;\n"
"    margin-left:0px;\n"
"    background-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgba(247, 247, 247, 255), stop:1 rgba(255, 255, 255, 255));\n"
"}\n"
"QTabBar::tab:selected, QTabBar::tab:last:selected, QTabBar::tab:hover {\n"
"      border-style: solid;\n"
"      border-left-width:1px;\n"
"    border-right-color: transparent;\n"
"    border-top-color: rgb(209,209,209);\n"
"    border-left-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgba(209, 209, 209, 209), stop:1 rgba(229, 229, 229, 229));\n"
"    border-bottom-color: rgb(229,229,229);\n"
"    color: #FFFFFF;\n"
"    padding: 3px;\n"
"    margin-left:0px;\n"
"    background-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgba(0, 113, 255, 255), stop:1 rgba(91, 171, 252, 255));\n"
"}\n"
"\n"
"QTabBar::tab:selected, QTabBar::tab:first:selected, QTabBar::tab:hover {\n"
"      border-style: solid;\n"
"      border-left-width:1px;\n"
"      border-bottom-width:1px;\n"
"      border-top-width:1px;\n"
"    border-right-color: transparent;\n"
"    border-top-color: rgb(209,209,209);\n"
"    border-left-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgba(209, 209, 209, 209), stop:1 rgba(229, 229, 229, 229));\n"
"    border-bottom-color: rgb(229,229,229);\n"
"    color: #FFFFFF;\n"
"    padding: 3px;\n"
"    margin-left:0px;\n"
"    background-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgba(0, 113, 255, 255), stop:1 rgba(91, 171, 252, 255));\n"
"}\n"
"\n"
"QCheckBox {\n"
"    color: #000000;\n"
"    padding: 2px;\n"
"}\n"
"QCheckBox:disabled {\n"
"    color: #808086;\n"
"    padding: 2px;\n"
"}\n"
"\n"
"QCheckBox:hover {\n"
"    border-radius:4px;\n"
"    border-style:solid;\n"
"    padding-left: 1px;\n"
"    padding-right: 1px;\n"
"    padding-bottom: 1px;\n"
"    padding-top: 1px;\n"
"    border-width:1px;\n"
"    border-color: transparent;\n"
"}\n"
"QCheckBox::indicator:checked {\n"
"\n"
"    height: 10px;\n"
"    width: 10px;\n"
"    border-style:solid;\n"
"    border-width: 1px;\n"
"    border-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgba(0, 113, 255, 255), stop:1 rgba(91, 171, 252, 255));\n"
"    color: #000000;\n"
"    background-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgba(0, 113, 255, 255), stop:1 rgba(91, 171, 252, 255));\n"
"}\n"
"QCheckBox::indicator:unchecked {\n"
"\n"
"    height: 10px;\n"
"    width: 10px;\n"
"    border-style:solid;\n"
"    border-width: 1px;\n"
"    border-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgba(0, 113, 255, 255), stop:1 rgba(91, 171, 252, 255));\n"
"    color: #000000;\n"
"}\n"
"QRadioButton {\n"
"    color: 000000;\n"
"    padding: 1px;\n"
"}\n"
"QRadioButton::indicator:checked {\n"
"    height: 10px;\n"
"    width: 10px;\n"
"    border-style:solid;\n"
"    border-radius:5px;\n"
"    border-width: 1px;\n"
"    border-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgba(0, 113, 255, 255), stop:1 rgba(91, 171, 252, 255));\n"
"    color: #a9b7c6;\n"
"    background-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgba(0, 113, 255, 255), stop:1 rgba(91, 171, 252, 255));\n"
"}\n"
"QRadioButton::indicator:!checked {\n"
"    height: 10px;\n"
"    width: 10px;\n"
"    border-style:solid;\n"
"    border-radius:5px;\n"
"    border-width: 1px;\n"
"    border-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgba(0, 113, 255, 255), stop:1 rgba(91, 171, 252, 255));\n"
"    color: #a9b7c6;\n"
"    background-color: transparent;\n"
"}\n"
"QStatusBar {\n"
"    color:#027f7f;\n"
"}\n"
"QSpinBox {\n"
"    border-style: solid;\n"
"    border-width: 1px;\n"
"    border-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgba(0, 113, 255, 255), stop:1 rgba(91, 171, 252, 255));\n"
"}\n"
"QDoubleSpinBox {\n"
"    border-style: solid;\n"
"    border-width: 1px;\n"
"    border-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgba(0, 113, 255, 255), stop:1 rgba(91, 171, 252, 255));\n"
"}\n"
"QTimeEdit {\n"
"    border-style: solid;\n"
"    border-width: 1px;\n"
"    border-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgba(0, 113, 255, 255), stop:1 rgba(91, 171, 252, 255));\n"
"}\n"
"QDateTimeEdit {\n"
"    border-style: solid;\n"
"    border-width: 1px;\n"
"    border-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgba(0, 113, 255, 255), stop:1 rgba(91, 171, 252, 255));\n"
"}\n"
"QDateEdit {\n"
"    border-style: solid;\n"
"    border-width: 1px;\n"
"    border-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgba(0, 113, 255, 255), stop:1 rgba(91, 171, 252, 255));\n"
"}\n"
"\n"
"QToolBox {\n"
"    color: #a9b7c6;\n"
"    background-color:#000000;\n"
"}\n"
"QToolBox::tab {\n"
"    color: #a9b7c6;\n"
"    background-color:#000000;\n"
"}\n"
"QToolBox::tab:selected {\n"
"    color: #FFFFFF;\n"
"    background-color:#000000;\n"
"}\n"
"QScrollArea {\n"
"    color: #FFFFFF;\n"
"    background-color:#000000;\n"
"}\n"
"QSlider::groove:horizontal {\n"
"    height: 5px;\n"
"    background-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgba(49, 147, 250, 255), stop:1 rgba(34, 142, 255, 255));\n"
"}\n"
"QSlider::groove:vertical {\n"
"    width: 5px;\n"
"    background-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgba(49, 147, 250, 255), stop:1 rgba(34, 142, 255, 255));\n"
"}\n"
"QSlider::handle:horizontal {\n"
"    background: rgb(253,253,253);\n"
"    border-style: solid;\n"
"    border-width: 1px;\n"
"    border-color: rgb(207,207,207);\n"
"    width: 12px;\n"
"    margin: -5px 0;\n"
"    border-radius: 7px;\n"
"}\n"
"QSlider::handle:vertical {\n"
"    background: rgb(253,253,253);\n"
"    border-style: solid;\n"
"    border-width: 1px;\n"
"    border-color: rgb(207,207,207);\n"
"    height: 12px;\n"
"    margin: 0 -5px;\n"
"    border-radius: 7px;\n"
"}\n"
"QSlider::add-page:horizontal {\n"
"    background: rgb(181,181,181);\n"
"}\n"
"QSlider::add-page:vertical {\n"
"    background: rgb(181,181,181);\n"
"}\n"
"QSlider::sub-page:horizontal {\n"
"    background-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgba(49, 147, 250, 255), stop:1 rgba(34, 142, 255, 255));\n"
"}\n"
"QSlider::sub-page:vertical {\n"
"    background-color: qlineargradient(spread:pad, y1:0.5, x1:1, y2:0.5, x2:0, stop:0 rgba(49, 147, 250, 255), stop:1 rgba(34, 142, 255, 255));\n"
"}\n"
"QScrollBar:horizontal {\n"
"    max-height: 20px;\n"
"    border: 1px transparent grey;\n"
"    margin: 0px 20px 0px 20px;\n"
"}\n"
"QScrollBar:vertical {\n"
"    max-width: 20px;\n"
"    border: 1px transparent grey;\n"
"    margin: 20px 0px 20px 0px;\n"
"}\n"
"QScrollBar::handle:horizontal {\n"
"    background: rgb(253,253,253);\n"
"    border-style: solid;\n"
"    border-width: 1px;\n"
"    border-color: rgb(207,207,207);\n"
"    border-radius: 7px;\n"
"    min-width: 25px;\n"
"}\n"
"QScrollBar::handle:horizontal:hover {\n"
"    background: rgb(253,253,253);\n"
"    border-style: solid;\n"
"    border-width: 1px;\n"
"    border-color: rgb(147, 200, 200);\n"
"    border-radius: 7px;\n"
"    min-width: 25px;\n"
"}\n"
"QScrollBar::handle:vertical {\n"
"    background: rgb(253,253,253);\n"
"    border-style: solid;\n"
"    border-width: 1px;\n"
"    border-color: rgb(207,207,207);\n"
"    border-radius: 7px;\n"
"    min-height: 25px;\n"
"}\n"
"QScrollBar::handle:vertical:hover {\n"
"    background: rgb(253,253,253);\n"
"    border-style: solid;\n"
"    border-width: 1px;\n"
"    border-color: rgb(147, 200, 200);\n"
"    border-radius: 7px;\n"
"    min-height: 25px;\n"
"}\n"
"QScrollBar::add-line:horizontal {\n"
"   border: 2px transparent grey;\n"
"   border-top-right-radius: 7px;\n"
"   border-bottom-right-radius: 7px;\n"
"   background: rgba(34, 142, 255, 255);\n"
"   width: 20px;\n"
"   subcontrol-position: right;\n"
"   subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::add-line:horizontal:pressed {\n"
"   border: 2px transparent grey;\n"
"   border-top-right-radius: 7px;\n"
"   border-bottom-right-radius: 7px;\n"
"   background: rgb(181,181,181);\n"
"   width: 20px;\n"
"   subcontrol-position: right;\n"
"   subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::add-line:vertical {\n"
"   border: 2px transparent grey;\n"
"   border-bottom-left-radius: 7px;\n"
"   border-bottom-right-radius: 7px;\n"
"   background: rgba(34, 142, 255, 255);\n"
"   height: 20px;\n"
"   subcontrol-position: bottom;\n"
"   subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::add-line:vertical:pressed {\n"
"   border: 2px transparent grey;\n"
"   border-bottom-left-radius: 7px;\n"
"   border-bottom-right-radius: 7px;\n"
"   background: rgb(181,181,181);\n"
"   height: 20px;\n"
"   subcontrol-position: bottom;\n"
"   subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::sub-line:horizontal {\n"
"   border: 2px transparent grey;\n"
"   border-top-left-radius: 7px;\n"
"   border-bottom-left-radius: 7px;\n"
"   background: rgba(34, 142, 255, 255);\n"
"   width: 20px;\n"
"   subcontrol-position: left;\n"
"   subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::sub-line:horizontal:pressed {\n"
"   border: 2px transparent grey;\n"
"   border-top-left-radius: 7px;\n"
"   border-bottom-left-radius: 7px;\n"
"   background: rgb(181,181,181);\n"
"   width: 20px;\n"
"   subcontrol-position: left;\n"
"   subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::sub-line:vertical {\n"
"   border: 2px transparent grey;\n"
"   border-top-left-radius: 7px;\n"
"   border-top-right-radius: 7px;\n"
"   background: rgba(34, 142, 255, 255);\n"
"   height: 20px;\n"
"   subcontrol-position: top;\n"
"   subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::sub-line:vertical:pressed {\n"
"   border: 2px transparent grey;\n"
"   border-top-left-radius: 7px;\n"
"   border-top-right-radius: 7px;\n"
"   background: rgb(181,181,181);\n"
"   height: 20px;\n"
"   subcontrol-position: top;\n"
"   subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::left-arrow:horizontal {\n"
"   border: 1px transparent grey;\n"
"   border-top-left-radius: 3px;\n"
"   border-bottom-left-radius: 3px;\n"
"   width: 6px;\n"
"   height: 6px;\n"
"   background: white;\n"
"}\n"
"QScrollBar::right-arrow:horizontal {\n"
"   border: 1px transparent grey;\n"
"   border-top-right-radius: 3px;\n"
"   border-bottom-right-radius: 3px;\n"
"   width: 6px;\n"
"   height: 6px;\n"
"   background: white;\n"
"}\n"
"QScrollBar::up-arrow:vertical {\n"
"   border: 1px transparent grey;\n"
"   border-top-left-radius: 3px;\n"
"   border-top-right-radius: 3px;\n"
"   width: 6px;\n"
"   height: 6px;\n"
"   background: white;\n"
"}\n"
"QScrollBar::down-arrow:vertical {\n"
"   border: 1px transparent grey;\n"
"   border-bottom-left-radius: 3px;\n"
"   border-bottom-right-radius: 3px;\n"
"   width: 6px;\n"
"   height: 6px;\n"
"   background: white;\n"
"}\n"
"QScrollBar::add-page:horizontal, QScrollBar::sub-page:horizontal {\n"
"   background: none;\n"
"}\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"   background: none;\n"
"}\n"
"\n"
"QTableView\n"
"{\n"
"    gridline-color: #BCBCBC;\n"
"    font-size: 12pt;\n"
"    font: bold italic large \"Times New Roman\";\n"
"}\n"
"\n"
"QTableView QTableCornerButton::section\n"
"{\n"
"    background-color: #FCFCFC;\n"
"    border: 1px solid #BCBCBC;\n"
"}\n"
"\n"
"QTableView::item::selected\n"
"{\n"
"    selection-background-color: #E6FFBF;\n"
"    selection-color:black;\n"
"}\n"
"\n"
"QTableView::item::hover\n"
"{\n"
"    background-color: #C8EDFF;\n"
"    selection-color:black;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.txt_Adres = QtWidgets.QLineEdit(self.centralwidget)
        self.txt_Adres.setGeometry(QtCore.QRect(673, 320, 131, 22))
        self.txt_Adres.setObjectName("txt_Adres")
        self.txt_Maas_Bilgisi = QtWidgets.QLineEdit(self.centralwidget)
        self.txt_Maas_Bilgisi.setGeometry(QtCore.QRect(673, 160, 131, 22))
        self.txt_Maas_Bilgisi.setObjectName("txt_Maas_Bilgisi")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(484, 71, 21, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.groupBox_7 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_7.setGeometry(QtCore.QRect(203, 310, 221, 41))
        self.groupBox_7.setTitle("")
        self.groupBox_7.setObjectName("groupBox_7")
        self.cmb_Egitim = QtWidgets.QComboBox(self.groupBox_7)
        self.cmb_Egitim.setGeometry(QtCore.QRect(60, 10, 108, 22))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.cmb_Egitim.setFont(font)
        self.cmb_Egitim.setObjectName("cmb_Egitim")
        self.cmb_Egitim.addItem("")
        self.cmb_Egitim.addItem("")
        self.cmb_Egitim.addItem("")
        self.cmb_Egitim.addItem("")
        self.cmb_Egitim.addItem("")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(53, 100, 38, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_20 = QtWidgets.QLabel(self.centralwidget)
        self.label_20.setGeometry(QtCore.QRect(23, 730, 81, 16))
        self.label_20.setObjectName("label_20")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(53, 290, 125, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(53, 70, 170, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.txt_Posta = QtWidgets.QLineEdit(self.centralwidget)
        self.txt_Posta.setGeometry(QtCore.QRect(673, 240, 131, 22))
        self.txt_Posta.setObjectName("txt_Posta")
        self.txt_Isim = QtWidgets.QLineEdit(self.centralwidget)
        self.txt_Isim.setGeometry(QtCore.QRect(293, 100, 131, 22))
        self.txt_Isim.setMaxLength(200)
        self.txt_Isim.setObjectName("txt_Isim")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(484, 99, 95, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.txt_Kimlik = QtWidgets.QLineEdit(self.centralwidget)
        self.txt_Kimlik.setGeometry(QtCore.QRect(293, 70, 131, 22))
        self.txt_Kimlik.setMaxLength(11)
        self.txt_Kimlik.setObjectName("txt_Kimlik")
        self.txt_Id = QtWidgets.QLineEdit(self.centralwidget)
        self.txt_Id.setGeometry(QtCore.QRect(673, 70, 131, 22))
        self.txt_Id.setObjectName("txt_Id")
        self.btn_Kayit_Ara = QtWidgets.QPushButton(self.centralwidget)
        self.btn_Kayit_Ara.setGeometry(QtCore.QRect(933, 170, 121, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.btn_Kayit_Ara.setFont(font)
        self.btn_Kayit_Ara.setObjectName("btn_Kayit_Ara")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(53, 320, 148, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(53, 260, 142, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(53, 130, 67, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(203, 190, 221, 31))
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.rb_Kadin = QtWidgets.QRadioButton(self.groupBox)
        self.rb_Kadin.setGeometry(QtCore.QRect(140, 10, 58, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.rb_Kadin.setFont(font)
        self.rb_Kadin.setObjectName("rb_Kadin")
        self.rb_Erkek = QtWidgets.QRadioButton(self.groupBox)
        self.rb_Erkek.setGeometry(QtCore.QRect(50, 10, 58, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.rb_Erkek.setFont(font)
        self.rb_Erkek.setCheckable(True)
        self.rb_Erkek.setObjectName("rb_Erkek")
        self.label_Adet = QtWidgets.QLabel(self.centralwidget)
        self.label_Adet.setGeometry(QtCore.QRect(103, 730, 55, 16))
        self.label_Adet.setText("")
        self.label_Adet.setObjectName("label_Adet")
        self.txt_Tel = QtWidgets.QLineEdit(self.centralwidget)
        self.txt_Tel.setGeometry(QtCore.QRect(673, 280, 131, 22))
        self.txt_Tel.setObjectName("txt_Tel")
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        self.label_13.setGeometry(QtCore.QRect(484, 130, 141, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(53, 230, 100, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.Tablo = QtWidgets.QTableWidget(self.centralwidget)
        self.Tablo.setGeometry(QtCore.QRect(40, 400, 1021, 331))
        self.Tablo.setStyleSheet("QTableView\n"
"{\n"
"    gridline-color: #BCBCBC;\n"
"    font-size: 12pt;\n"
"    font: bold italic large \"Times New Roman\";\n"
"}\n"
"\n"
"QTableView QTableCornerButton::section\n"
"{\n"
"    background-color: #FCFCFC;\n"
"    border: 1px solid #BCBCBC;\n"
"}\n"
"\n"
"QTableView::item::selected\n"
"{\n"
"    selection-background-color: #E6FFBF;\n"
"    selection-color:black;\n"
"}\n"
"\n"
"QTableView::item::hover\n"
"{\n"
"    background-color: #C8EDFF;\n"
"    selection-color:black;\n"
"}")
        self.Tablo.setLineWidth(1)
        self.Tablo.setAutoScrollMargin(16)
        self.Tablo.setShowGrid(True)
        self.Tablo.setGridStyle(QtCore.Qt.SolidLine)
        self.Tablo.setRowCount(50)
        self.Tablo.setColumnCount(16)
        self.Tablo.setObjectName("Tablo")
        self.Tablo.horizontalHeader().setDefaultSectionSize(200)
        self.Tablo.horizontalHeader().setMinimumSectionSize(200)
        self.txt_Soyisim = QtWidgets.QLineEdit(self.centralwidget)
        self.txt_Soyisim.setGeometry(QtCore.QRect(293, 130, 131, 22))
        self.txt_Soyisim.setMaxLength(200)
        self.txt_Soyisim.setObjectName("txt_Soyisim")
        self.label_16 = QtWidgets.QLabel(self.centralwidget)
        self.label_16.setGeometry(QtCore.QRect(473, 280, 161, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.groupBox_4 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_4.setGeometry(QtCore.QRect(203, 220, 221, 31))
        self.groupBox_4.setTitle("")
        self.groupBox_4.setObjectName("groupBox_4")
        self.rb_Bekar = QtWidgets.QRadioButton(self.groupBox_4)
        self.rb_Bekar.setGeometry(QtCore.QRect(50, 10, 59, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.rb_Bekar.setFont(font)
        self.rb_Bekar.setObjectName("rb_Bekar")
        self.rb_Evli = QtWidgets.QRadioButton(self.groupBox_4)
        self.rb_Evli.setGeometry(QtCore.QRect(140, 10, 46, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.rb_Evli.setFont(font)
        self.rb_Evli.setObjectName("rb_Evli")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(53, 200, 68, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.groupBox_6 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_6.setGeometry(QtCore.QRect(203, 280, 221, 31))
        self.groupBox_6.setTitle("")
        self.groupBox_6.setObjectName("groupBox_6")
        self.cb_Ehliyet = QtWidgets.QCheckBox(self.groupBox_6)
        self.cb_Ehliyet.setGeometry(QtCore.QRect(90, 10, 47, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.cb_Ehliyet.setFont(font)
        self.cb_Ehliyet.setObjectName("cb_Ehliyet")
        self.txt_Calisma_Saatleri = QtWidgets.QLineEdit(self.centralwidget)
        self.txt_Calisma_Saatleri.setGeometry(QtCore.QRect(673, 130, 131, 22))
        self.txt_Calisma_Saatleri.setObjectName("txt_Calisma_Saatleri")
        self.label_18 = QtWidgets.QLabel(self.centralwidget)
        self.label_18.setGeometry(QtCore.QRect(483, 30, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.label_18.setFont(font)
        self.label_18.setObjectName("label_18")
        self.btn_Guncelle = QtWidgets.QPushButton(self.centralwidget)
        self.btn_Guncelle.setGeometry(QtCore.QRect(933, 220, 121, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.btn_Guncelle.setFont(font)
        self.btn_Guncelle.setObjectName("btn_Guncelle")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(484, 160, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(53, 169, 115, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_15 = QtWidgets.QLabel(self.centralwidget)
        self.label_15.setGeometry(QtCore.QRect(473, 240, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.label_17 = QtWidgets.QLabel(self.centralwidget)
        self.label_17.setGeometry(QtCore.QRect(473, 320, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.label_19 = QtWidgets.QLabel(self.centralwidget)
        self.label_19.setGeometry(QtCore.QRect(473, 200, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.label_19.setFont(font)
        self.label_19.setObjectName("label_19")
        self.label_14 = QtWidgets.QLabel(self.centralwidget)
        self.label_14.setGeometry(QtCore.QRect(53, 30, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.btn_Kayit_Sil = QtWidgets.QPushButton(self.centralwidget)
        self.btn_Kayit_Sil.setGeometry(QtCore.QRect(933, 110, 121, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.btn_Kayit_Sil.setFont(font)
        self.btn_Kayit_Sil.setObjectName("btn_Kayit_Sil")
        self.groupBox_5 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_5.setGeometry(QtCore.QRect(203, 250, 221, 31))
        self.groupBox_5.setTitle("")
        self.groupBox_5.setObjectName("groupBox_5")
        self.rb_Askerlik_yapildi = QtWidgets.QRadioButton(self.groupBox_5)
        self.rb_Askerlik_yapildi.setGeometry(QtCore.QRect(10, 10, 64, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.rb_Askerlik_yapildi.setFont(font)
        self.rb_Askerlik_yapildi.setObjectName("rb_Askerlik_yapildi")
        self.rb_Askerlik_Tecilli = QtWidgets.QRadioButton(self.groupBox_5)
        self.rb_Askerlik_Tecilli.setGeometry(QtCore.QRect(80, 10, 81, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.rb_Askerlik_Tecilli.setFont(font)
        self.rb_Askerlik_Tecilli.setObjectName("rb_Askerlik_Tecilli")
        self.rb_Askerlik_Muaf = QtWidgets.QRadioButton(self.groupBox_5)
        self.rb_Askerlik_Muaf.setGeometry(QtCore.QRect(160, 10, 56, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.rb_Askerlik_Muaf.setFont(font)
        self.rb_Askerlik_Muaf.setObjectName("rb_Askerlik_Muaf")
        self.btn_Kayit_Listele = QtWidgets.QPushButton(self.centralwidget)
        self.btn_Kayit_Listele.setGeometry(QtCore.QRect(933, 270, 121, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.btn_Kayit_Listele.setFont(font)
        self.btn_Kayit_Listele.setObjectName("btn_Kayit_Listele")
        self.btn_Kayit_Ekle = QtWidgets.QPushButton(self.centralwidget)
        self.btn_Kayit_Ekle.setGeometry(QtCore.QRect(933, 60, 121, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.btn_Kayit_Ekle.setFont(font)
        self.btn_Kayit_Ekle.setObjectName("btn_Kayit_Ekle")
        self.cmb_Departman = QtWidgets.QComboBox(self.centralwidget)
        self.cmb_Departman.setGeometry(QtCore.QRect(680, 100, 121, 22))
        self.cmb_Departman.setObjectName("cmb_Departman")
        self.cmb_Departman.addItem("")
        self.cmb_Departman.addItem("")
        self.cmb_Departman.addItem("")
        self.cmb_Departman.addItem("")
        self.cmb_Departman.addItem("")
        self.cmb_Departman.addItem("")
        self.cmb_Departman.addItem("")
        self.cmb_Departman.addItem("")
        self.gbox_Dogumgunu = QtWidgets.QGroupBox(self.centralwidget)
        self.gbox_Dogumgunu.setGeometry(QtCore.QRect(200, 150, 221, 41))
        self.gbox_Dogumgunu.setTitle("")
        self.gbox_Dogumgunu.setObjectName("gbox_Dogumgunu")
        self.cmb_Yil = QtWidgets.QComboBox(self.gbox_Dogumgunu)
        self.cmb_Yil.setGeometry(QtCore.QRect(147, 10, 58, 22))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.cmb_Yil.setFont(font)
        self.cmb_Yil.setObjectName("cmb_Yil")
        self.cmb_Yil.addItem("")
        self.cmb_Yil.addItem("")
        self.cmb_Yil.addItem("")
        self.cmb_Yil.addItem("")
        self.cmb_Yil.addItem("")
        self.cmb_Yil.addItem("")
        self.cmb_Yil.addItem("")
        self.cmb_Yil.addItem("")
        self.cmb_Yil.addItem("")
        self.cmb_Yil.addItem("")
        self.cmb_Yil.addItem("")
        self.cmb_Yil.addItem("")
        self.cmb_Yil.addItem("")
        self.cmb_Yil.addItem("")
        self.cmb_Yil.addItem("")
        self.cmb_Yil.addItem("")
        self.cmb_Yil.addItem("")
        self.cmb_Yil.addItem("")
        self.cmb_Yil.addItem("")
        self.cmb_Yil.addItem("")
        self.cmb_Yil.addItem("")
        self.cmb_Yil.addItem("")
        self.cmb_Yil.addItem("")
        self.cmb_Yil.addItem("")
        self.cmb_Yil.addItem("")
        self.cmb_Ay = QtWidgets.QComboBox(self.gbox_Dogumgunu)
        self.cmb_Ay.setGeometry(QtCore.QRect(60, 10, 80, 22))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.cmb_Ay.setFont(font)
        self.cmb_Ay.setObjectName("cmb_Ay")
        self.cmb_Ay.addItem("")
        self.cmb_Ay.addItem("")
        self.cmb_Ay.addItem("")
        self.cmb_Ay.addItem("")
        self.cmb_Ay.addItem("")
        self.cmb_Ay.addItem("")
        self.cmb_Ay.addItem("")
        self.cmb_Ay.addItem("")
        self.cmb_Ay.addItem("")
        self.cmb_Ay.addItem("")
        self.cmb_Ay.addItem("")
        self.cmb_Ay.addItem("")
        self.cmb_Gun = QtWidgets.QComboBox(self.gbox_Dogumgunu)
        self.cmb_Gun.setEnabled(True)
        self.cmb_Gun.setGeometry(QtCore.QRect(9, 10, 44, 22))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.cmb_Gun.setFont(font)
        self.cmb_Gun.setStatusTip("")
        self.cmb_Gun.setObjectName("cmb_Gun")
        self.cmb_Gun.addItem("")
        self.cmb_Gun.addItem("")
        self.cmb_Gun.addItem("")
        self.cmb_Gun.addItem("")
        self.cmb_Gun.addItem("")
        self.cmb_Gun.addItem("")
        self.cmb_Gun.addItem("")
        self.cmb_Gun.addItem("")
        self.cmb_Gun.addItem("")
        self.cmb_Gun.addItem("")
        self.cmb_Gun.addItem("")
        self.cmb_Gun.addItem("")
        self.cmb_Gun.addItem("")
        self.cmb_Gun.addItem("")
        self.cmb_Gun.addItem("")
        self.cmb_Gun.addItem("")
        self.cmb_Gun.addItem("")
        self.cmb_Gun.addItem("")
        self.cmb_Gun.addItem("")
        self.cmb_Gun.addItem("")
        self.cmb_Gun.addItem("")
        self.cmb_Gun.addItem("")
        self.cmb_Gun.addItem("")
        self.cmb_Gun.addItem("")
        self.cmb_Gun.addItem("")
        self.cmb_Gun.addItem("")
        self.cmb_Gun.addItem("")
        self.cmb_Gun.addItem("")
        self.cmb_Gun.addItem("")
        self.cmb_Gun.addItem("")
        self.cmb_Gun.addItem("")
        self.btn_Cikis = QtWidgets.QPushButton(self.centralwidget)
        self.btn_Cikis.setGeometry(QtCore.QRect(940, 310, 111, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.btn_Cikis.setFont(font)
        self.btn_Cikis.setObjectName("btn_Cikis")
        self.gbox_Dogumgunu.raise_()
        self.txt_Adres.raise_()
        self.txt_Maas_Bilgisi.raise_()
        self.label.raise_()
        self.groupBox_7.raise_()
        self.label_3.raise_()
        self.label_20.raise_()
        self.label_9.raise_()
        self.label_2.raise_()
        self.txt_Posta.raise_()
        self.txt_Isim.raise_()
        self.label_11.raise_()
        self.txt_Kimlik.raise_()
        self.txt_Id.raise_()
        self.btn_Kayit_Ara.raise_()
        self.label_10.raise_()
        self.label_8.raise_()
        self.label_4.raise_()
        self.groupBox.raise_()
        self.label_Adet.raise_()
        self.txt_Tel.raise_()
        self.label_13.raise_()
        self.label_7.raise_()
        self.Tablo.raise_()
        self.txt_Soyisim.raise_()
        self.label_16.raise_()
        self.groupBox_4.raise_()
        self.label_6.raise_()
        self.groupBox_6.raise_()
        self.txt_Calisma_Saatleri.raise_()
        self.label_18.raise_()
        self.btn_Guncelle.raise_()
        self.label_12.raise_()
        self.label_5.raise_()
        self.label_15.raise_()
        self.label_17.raise_()
        self.label_19.raise_()
        self.label_14.raise_()
        self.btn_Kayit_Sil.raise_()
        self.groupBox_5.raise_()
        self.btn_Kayit_Listele.raise_()
        self.btn_Kayit_Ekle.raise_()
        self.cmb_Departman.raise_()
        self.btn_Cikis.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1093, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.cmb_Departman.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "ID"))
        self.cmb_Egitim.setItemText(0, _translate("MainWindow", "İlkokul"))
        self.cmb_Egitim.setItemText(1, _translate("MainWindow", "Ortaokul"))
        self.cmb_Egitim.setItemText(2, _translate("MainWindow", "Lise"))
        self.cmb_Egitim.setItemText(3, _translate("MainWindow", "Lisans"))
        self.cmb_Egitim.setItemText(4, _translate("MainWindow", "Yüksek Lisans"))
        self.label_3.setText(_translate("MainWindow", "İsim"))
        self.label_20.setText(_translate("MainWindow", "Kayıt Sayısı :"))
        self.label_9.setText(_translate("MainWindow", "Ehliyet Belgesi"))
        self.label_2.setText(_translate("MainWindow", "T.C Kimlik Numarası"))
        self.label_11.setText(_translate("MainWindow", "Departman"))
        self.btn_Kayit_Ara.setText(_translate("MainWindow", "Kayıt Ara"))
        self.label_10.setText(_translate("MainWindow", "Öğrenim Seviyesi"))
        self.label_8.setText(_translate("MainWindow", "Askerlik Durumu"))
        self.label_4.setText(_translate("MainWindow", "Soyisim"))
        self.rb_Kadin.setText(_translate("MainWindow", "Kadın"))
        self.rb_Erkek.setText(_translate("MainWindow", "Erkek"))
        self.label_13.setText(_translate("MainWindow", "Çalışma Saatleri"))
        self.label_7.setText(_translate("MainWindow", "Medeni Hali"))
        self.label_16.setText(_translate("MainWindow", "Telefon Numarası"))
        self.rb_Bekar.setText(_translate("MainWindow", "Bekar"))
        self.rb_Evli.setText(_translate("MainWindow", "Evli"))
        self.label_6.setText(_translate("MainWindow", "Cinsiyet"))
        self.cb_Ehliyet.setText(_translate("MainWindow", "Var"))
        self.label_18.setText(_translate("MainWindow", "İş Bilgileri"))
        self.btn_Guncelle.setText(_translate("MainWindow", "Güncelle"))
        self.label_12.setText(_translate("MainWindow", "Maaş Bilgisi"))
        self.label_5.setText(_translate("MainWindow", "Doğum Tarihi"))
        self.label_15.setText(_translate("MainWindow", "e-posta"))
        self.label_17.setText(_translate("MainWindow", "Adres"))
        self.label_19.setText(_translate("MainWindow", "İletişim Bilgileri"))
        self.label_14.setText(_translate("MainWindow", "Kişisel Bilgiler  "))
        self.btn_Kayit_Sil.setText(_translate("MainWindow", "Kayıt Sil"))
        self.rb_Askerlik_yapildi.setText(_translate("MainWindow", "Yapıldı"))
        self.rb_Askerlik_Tecilli.setText(_translate("MainWindow", "Yapılmadı"))
        self.rb_Askerlik_Muaf.setText(_translate("MainWindow", "Muaf"))
        self.btn_Kayit_Listele.setText(_translate("MainWindow", "Kayıt Listele"))
        self.btn_Kayit_Ekle.setText(_translate("MainWindow", "Kayıt Ekle"))
        self.cmb_Departman.setItemText(0, _translate("MainWindow", "AR-GE"))
        self.cmb_Departman.setItemText(1, _translate("MainWindow", "Halkla ilişkiler"))
        self.cmb_Departman.setItemText(2, _translate("MainWindow", "Hukuk"))
        self.cmb_Departman.setItemText(3, _translate("MainWindow", "İnsan kaynakları"))
        self.cmb_Departman.setItemText(4, _translate("MainWindow", "Pazarlama"))
        self.cmb_Departman.setItemText(5, _translate("MainWindow", "Üretim"))
        self.cmb_Departman.setItemText(6, _translate("MainWindow", "Finans"))
        self.cmb_Departman.setItemText(7, _translate("MainWindow", "Muhasebe"))
        self.cmb_Yil.setCurrentText(_translate("MainWindow", "1981"))
        self.cmb_Yil.setItemText(0, _translate("MainWindow", "1980"))
        self.cmb_Yil.setItemText(1, _translate("MainWindow", "1981"))
        self.cmb_Yil.setItemText(2, _translate("MainWindow", "1982"))
        self.cmb_Yil.setItemText(3, _translate("MainWindow", "1983"))
        self.cmb_Yil.setItemText(4, _translate("MainWindow", "1984"))
        self.cmb_Yil.setItemText(5, _translate("MainWindow", "1985"))
        self.cmb_Yil.setItemText(6, _translate("MainWindow", "1986"))
        self.cmb_Yil.setItemText(7, _translate("MainWindow", "1987"))
        self.cmb_Yil.setItemText(8, _translate("MainWindow", "1988"))
        self.cmb_Yil.setItemText(9, _translate("MainWindow", "1989"))
        self.cmb_Yil.setItemText(10, _translate("MainWindow", "1990"))
        self.cmb_Yil.setItemText(11, _translate("MainWindow", "1991"))
        self.cmb_Yil.setItemText(12, _translate("MainWindow", "1992"))
        self.cmb_Yil.setItemText(13, _translate("MainWindow", "1993"))
        self.cmb_Yil.setItemText(14, _translate("MainWindow", "1994"))
        self.cmb_Yil.setItemText(15, _translate("MainWindow", "1995"))
        self.cmb_Yil.setItemText(16, _translate("MainWindow", "1996"))
        self.cmb_Yil.setItemText(17, _translate("MainWindow", "1997"))
        self.cmb_Yil.setItemText(18, _translate("MainWindow", "1998"))
        self.cmb_Yil.setItemText(19, _translate("MainWindow", "1999"))
        self.cmb_Yil.setItemText(20, _translate("MainWindow", "2000"))
        self.cmb_Yil.setItemText(21, _translate("MainWindow", "2001"))
        self.cmb_Yil.setItemText(22, _translate("MainWindow", "2002"))
        self.cmb_Yil.setItemText(23, _translate("MainWindow", "2003"))
        self.cmb_Yil.setItemText(24, _translate("MainWindow", "2004"))
        self.cmb_Ay.setCurrentText(_translate("MainWindow", "Ocak   "))
        self.cmb_Ay.setItemText(0, _translate("MainWindow", "Ocak   "))
        self.cmb_Ay.setItemText(1, _translate("MainWindow", "Şubat  "))
        self.cmb_Ay.setItemText(2, _translate("MainWindow", "Mart   "))
        self.cmb_Ay.setItemText(3, _translate("MainWindow", "Nisan  "))
        self.cmb_Ay.setItemText(4, _translate("MainWindow", "Mayıs  "))
        self.cmb_Ay.setItemText(5, _translate("MainWindow", "Haziran"))
        self.cmb_Ay.setItemText(6, _translate("MainWindow", "Temmuz "))
        self.cmb_Ay.setItemText(7, _translate("MainWindow", "Ağustos"))
        self.cmb_Ay.setItemText(8, _translate("MainWindow", "Eylül  "))
        self.cmb_Ay.setItemText(9, _translate("MainWindow", "Ekim   "))
        self.cmb_Ay.setItemText(10, _translate("MainWindow", "Kasım  "))
        self.cmb_Ay.setItemText(11, _translate("MainWindow", "Aralık "))
        self.cmb_Gun.setCurrentText(_translate("MainWindow", "01"))
        self.cmb_Gun.setItemText(0, _translate("MainWindow", "01"))
        self.cmb_Gun.setItemText(1, _translate("MainWindow", "02"))
        self.cmb_Gun.setItemText(2, _translate("MainWindow", "03"))
        self.cmb_Gun.setItemText(3, _translate("MainWindow", "04"))
        self.cmb_Gun.setItemText(4, _translate("MainWindow", "05"))
        self.cmb_Gun.setItemText(5, _translate("MainWindow", "06"))
        self.cmb_Gun.setItemText(6, _translate("MainWindow", "07"))
        self.cmb_Gun.setItemText(7, _translate("MainWindow", "08"))
        self.cmb_Gun.setItemText(8, _translate("MainWindow", "09"))
        self.cmb_Gun.setItemText(9, _translate("MainWindow", "10"))
        self.cmb_Gun.setItemText(10, _translate("MainWindow", "11"))
        self.cmb_Gun.setItemText(11, _translate("MainWindow", "12"))
        self.cmb_Gun.setItemText(12, _translate("MainWindow", "13"))
        self.cmb_Gun.setItemText(13, _translate("MainWindow", "14"))
        self.cmb_Gun.setItemText(14, _translate("MainWindow", "15"))
        self.cmb_Gun.setItemText(15, _translate("MainWindow", "16"))
        self.cmb_Gun.setItemText(16, _translate("MainWindow", "17"))
        self.cmb_Gun.setItemText(17, _translate("MainWindow", "18"))
        self.cmb_Gun.setItemText(18, _translate("MainWindow", "19"))
        self.cmb_Gun.setItemText(19, _translate("MainWindow", "20"))
        self.cmb_Gun.setItemText(20, _translate("MainWindow", "21"))
        self.cmb_Gun.setItemText(21, _translate("MainWindow", "22"))
        self.cmb_Gun.setItemText(22, _translate("MainWindow", "23"))
        self.cmb_Gun.setItemText(23, _translate("MainWindow", "24"))
        self.cmb_Gun.setItemText(24, _translate("MainWindow", "25"))
        self.cmb_Gun.setItemText(25, _translate("MainWindow", "26"))
        self.cmb_Gun.setItemText(26, _translate("MainWindow", "27"))
        self.cmb_Gun.setItemText(27, _translate("MainWindow", "28"))
        self.cmb_Gun.setItemText(28, _translate("MainWindow", "29"))
        self.cmb_Gun.setItemText(29, _translate("MainWindow", "30"))
        self.cmb_Gun.setItemText(30, _translate("MainWindow", "31"))
        self.btn_Cikis.setText(_translate("MainWindow", "Çıkış"))
