# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login_python.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(485, 411)
        self.btn_giris = QtWidgets.QPushButton(Form)
        self.btn_giris.setGeometry(QtCore.QRect(180, 250, 111, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.btn_giris.setFont(font)
        self.btn_giris.setObjectName("btn_giris")
        self.kullanici_adi = QtWidgets.QLabel(Form)
        self.kullanici_adi.setGeometry(QtCore.QRect(72, 72, 111, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.kullanici_adi.setFont(font)
        self.kullanici_adi.setObjectName("kullanici_adi")
        self.sifre = QtWidgets.QLabel(Form)
        self.sifre.setGeometry(QtCore.QRect(72, 100, 40, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.sifre.setFont(font)
        self.sifre.setObjectName("sifre")
        self.txt_kullanici_adi = QtWidgets.QLineEdit(Form)
        self.txt_kullanici_adi.setGeometry(QtCore.QRect(230, 71, 137, 22))
        self.txt_kullanici_adi.setObjectName("txt_kullanici_adi")
        self.txt_sifre = QtWidgets.QLineEdit(Form)
        self.txt_sifre.setGeometry(QtCore.QRect(230, 100, 137, 22))
        self.txt_sifre.setEchoMode(QtWidgets.QLineEdit.Password)
        self.txt_sifre.setObjectName("txt_sifre")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.btn_giris.setText(_translate("Form", "Giriş Yap"))
        self.kullanici_adi.setText(_translate("Form", "Kullanıcı Adı "))
        self.sifre.setText(_translate("Form", "Şifre"))

